using Pkg
Pkg.add("Plots")
Pkg.add("PyPlot")
Pkg.add("StatsPlots")
Pkg.add("Distributions")
Pkg.add("LaTeXStrings")
Pkg.add("Optim")
Pkg.add("BSON")
Pkg.add("DataFrames")
Pkg.add("CSV")
Pkg.add("Pluto")
Pkg.add("Images")
Pkg.add("ImageIO")
Pkg.add("FileIO")
Pkg.add("ImageShow")
Pkg.add("BenchmarkTools")
Pkg.update()
